apiVersion: apps/v1
kind: Deployment
metadata:
  name: sava-order
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: sava-order
        image: vampio/sava-order:0.1.1
        ports:
        - name: http
          containerPort: 9090
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: PORT
          value: 9090
        envFrom:
        - configMapRef:
            name: sava-order-configmap